export const state = {
    selectedSongId: null,
    allSongs: [],
    ws: null,
    mobileWs: null,
    transcriptionActiveTimer: null,
    audioContext: null,
    currentSegments: null,
    currentSegmentData: null,
    lastSegmentLyricsTimed: null,
    animationId: null,
    syncOffset: 0,
    isFirstSegment: true,
    totalPauseDuration: 0,
    pauseStartTarget: 0,
    isMobileMicrophoneConnected: false,
    localStreamForced: false,
    micSourceMode: 'pc',
    isSingingActive: false,
    isOutroActive: false,
    outroStartPlayerTime: 0,
    outroTotalDuration: 0,
    micMuted: false,
    activeUploadTab: 'youtube',
};
